"""The planning horizon is bounded by the table, not only by the form.

`20260924_0079` added `plan_horizon_hours` with a check constraint declared on
the model - and on SQLite a batch `add_column` copies the table as it is
reflected, so the constraint reached new databases and not this one. The
column was bounded by Pydantic at the two routes that write it and by nothing
at all underneath, which is exactly the gap a check constraint exists to
close: a value of zero would make the planner fill a window of no length and
a campaign would quietly stop posting.

Recreating the table is how SQLite adds a constraint. Named here rather than
left to Alembic's autogenerated copy so the other constraints travel with it.

Revision ID: 20260924_0080
Revises: 20260924_0079
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260924_0080"
down_revision: str | Sequence[str] | None = "20260924_0079"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Every check the table carries once this has run. The four that were already
#: there are repeated because recreating the table is how SQLite gains one,
#: and a copy that listed only the new one would silently drop the rest.
CHECKS = (
    ("valid_autopilot_recycle", "min_recycle_days BETWEEN 1 AND 365"),
    ("valid_autopilot_cap", "daily_cap_per_account BETWEEN 1 AND 24"),
    ("valid_autopilot_horizon", "plan_horizon_hours BETWEEN 1 AND 336"),
    ("valid_autopilot_delivery", "delivery IN ('draft','schedule','now')"),
    ("valid_autopilot_offer_mode", "offer_mode IN ('smart','manual','none')"),
    (
        "valid_autopilot_authority",
        "authority IN ('assist','auto_draft','run_by_exception','autonomous')",
    ),
)


def upgrade() -> None:
    # Anything already outside the bound would fail the copy. Nothing can be,
    # since the column was added with a server default of 24 and both writers
    # validate - but a table rebuild is not the place to find out.
    op.execute(
        "UPDATE campaign_autopilot SET plan_horizon_hours = 24 "
        "WHERE plan_horizon_hours IS NULL "
        "OR plan_horizon_hours < 1 OR plan_horizon_hours > 336"
    )
    with op.batch_alter_table(
        "campaign_autopilot",
        table_kwargs={"sqlite_autoincrement": False},
    ) as batch:
        for name, condition in CHECKS:
            batch.create_check_constraint(name, sa.text(condition))


def downgrade() -> None:
    with op.batch_alter_table("campaign_autopilot") as batch:
        batch.drop_constraint("valid_autopilot_horizon", type_="check")
